# Default values for uffizzi-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  uffizzi:
    controller:
      username: username
      password: ChangeMeNow

cert-manager: # dependency
  enabled: true
  installCRDs: true

ingress-nginx:
  controller:
    ingressClassResource:
      name: uffizzi
    enableAnnotationValidations: true # CVE-2023-5043 CVE-2023-5044
    config:
      proxy-body-size: "100m"
      proxy-buffer-size: "128k"
      strict-validate-path-type: true # CVE-2022-4886
    extraArgs:
      enable-ssl-passthrough: true

certEmail: "user@example.com"

clusterIssuer: "letsencrypt"

image: uffizzi/controller:latest

ingress:
  hostname: controller.uffizzi.example.com

zerossl:
  eab:
    hmacKey: foo
    keyId: bar

env: "production"

sandbox: "false"
