# Default values for uffizzi-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  uffizzi:
    controller:
      username: username
      password: ChangeMeNow

cert-manager: # dependency
  installCRDs: true

clusterIssuer: "zerossl"

image: uffizzicloud/uffizzi-controller:latest
ingress:
  hostname: uffizzi.example.com

podCidr: 10.0.0.0/8

eab:
  hmacKey: foo
  keyId: bar

env: "production"

sandbox: "false"
