# Default values for uffizzi-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  uffizzi:
    controller:
      username: username
      password: ChangeMeNow

cert-manager: # dependency
  enabled: true
  installCRDs: true

ingress-nginx:
  controller:
    extraArgs:
      enable-ssl-passthrough: true

certEmail: "user@example.com"

clusterIssuer: "letsencrypt"

image: uffizzi/controller:latest

ingress:
  hostname: controller.uffizzi.example.com

zerossl:
  eab:
    hmacKey: foo
    keyId: bar

env: "production"

sandbox: "false"
