# Default values for uffizzi-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  uffizzi:
    controller:
      username: username
      password: ChangeMeNow

cert-manager: # dependency
  installCRDs: true

certEmail: "user@example.com"

clusterIssuer: "letsencrypt"

image: uffizzi/controller:latest

ingress:
  hostname: controller.uffizzi.example.com

podCidr: 10.0.0.0/8

zerossl:
  eab:
    hmacKey: foo
    keyId: bar

env: "production"

sandbox: "false"
