---
global:
  uffizzi:
    controller:
      username: username
      password: ChangeMeNow
cert-manager:
  enabled: true
  installCRDs: true
ingress-nginx:
  controller:
    enableAnnotationValidations: true
    config:
      proxy-body-size: 100m
      proxy-buffer-size: 128k
      strict-validate-path-type: true
    extraArgs:
      enable-ssl-passthrough: true
certEmail: user@example.com
clusterIssuer: letsencrypt
image: uffizzi/controller:2.3.1
ingress:
  hostname: controller.uffizzi.example.com
zerossl:
  eab:
    hmacKey: foo
    keyId: bar
env: production
sandbox: 'false'
