apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Release.Name }}-zerossl
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "99"
spec:
  acme:
    email: {{ .Values.certEmail }}
    externalAccountBinding:
      keyID: {{ .Values.zerossl.eab.keyId }}
      keyAlgorithm: HS256
      keySecretRef:
        key: eab_hmac_key
        name: {{ .Release.Name }}-zerossl-eab-secret
    preferredChain: ""
    privateKeySecretRef:
      name: {{ .Release.Name }}-zerossl-tls
    server: https://acme.zerossl.com/v2/DV90
    solvers:
    - http01:
        ingress:
          class: nginx
