apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-controller-secret-env
type: Opaque
data:
  CONTROLLER_LOGIN: {{ .Values.global.uffizzi.controller.username | b64enc }}
  CONTROLLER_PASSWORD: {{ .Values.global.uffizzi.controller.password | b64enc }}
  ENV: {{ .Values.env | b64enc }}
  CERT_MANAGER_CLUSTER_ISSUER: {{ print .Release.Name "-" .Values.clusterIssuer | b64enc }}
  SANDBOX_ENABLED: {{ .Values.sandbox | b64enc }}
  TLS_PER_DEPLOYMENT_ENABLED: {{ .Values.tlsPerDeploymentEnabled | b64enc }}
