apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}-controller
  name: {{ .Release.Name }}-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-controller
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    annotations:
      checksum/config: {{ include (print $.Template.BasePath "/controller-secret-env.yaml") . | sha256sum }}
    metadata:
      labels:
        app: {{ .Release.Name }}-controller
    spec:
      automountServiceAccountToken: true
      serviceAccountName: {{ .Release.Name }}-controller
      enableServiceLinks: true
      shareProcessNamespace: false
      containers:
      - envFrom:
        - secretRef:
            name: {{ .Release.Name }}-controller-secret-env
            optional: false
        env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        image: {{ .Values.image }}
        imagePullPolicy: Always
        name: controller
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 192Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
