apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-controller
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ .Release.Name }}-controller
  sessionAffinity: None
  type: NodePort
