on:
  workflow_call:
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: uffizzi/controller
          tags: |
            type=raw,value=${{ github.sha }},enable=${{ github.ref_name == 'main' ||  github.ref_name == 'qa'}}
            type=raw,value=latest,enable=${{ github.ref_name == 'main' }}
            type=ref,event=branch,enable=${{ github.ref_name == 'qa' }}
            type=ref,event=pr
      - name: Build and Push Image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Update Docker Hub Description for Default Branch
        uses: peter-evans/dockerhub-description@v2.4.3
        if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: uffizzi/controller
