on:
  workflow_call:
env:
  CI_REPO_URL: "${{ secrets.CI_REPO_URL }}"
jobs:
  build-and-push-cotroller:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/uffizzicloud/controller_toolbox:v1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: gacts/github-slug@v1
        id: slug
      - name: Create toolbox env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          directory: infrastructure/toolbox
          file_name: secrets.env
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.CI_IDENTITY_PROVIDER_LOCATION }}
          service_account: ${{ secrets.CI_SERVICE_ACCOUNT_NAME }}
      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      - name: Build and Push controller
        run: |
          export CI_COMMIT_REF_SLUG=${{ steps.slug.outputs.branch-name-slug }}
          make build_controller push_controller
