on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      project_id:
        required: true
        type: string
      service_account_name:
        required: true
        type: string
      workload_identity_provider_name:
        required: true
        type: string
      image_name:
        required: true
        type: string

env:
  ENV: "${{ inputs.env }}"
  SENTRY_AUTH_TOKEN: "${{ secrets.SENTRY_AUTH_TOKEN }}"
  SENTRY_ORG: "${{ secrets.SENTRY_ORG }}"
  SENTRY_PROJECT: "${{ secrets.SENTRY_PROJECT }}"
  GCP_PROJECT_ID: "${{ inputs.project_id }}"

jobs:
  update-gke-controller:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/uffizzicloud/controller_toolbox:v2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: ${{ secrets[inputs.workload_identity_provider_name] }}
          service_account: ${{ secrets[inputs.service_account_name] }}
      - uses: 'google-github-actions/get-gke-credentials@v0'
        with:
          cluster_name: uffizzi-client
          location: us-central1
      - name: Update gke controller
        run: |
          export CONTROLLER_IMAGE=${{ inputs.image_name }}
          make update_gke_controller_service

# ----------- sentry release and notification -----------

  create-sentry-release:
    needs:
      - update-gke-controller
    uses: ./.github/workflows/sentry-release.yml
    with:
      env: ${{ inputs.env }}
      sentry_org: uffizzi-cloud
      sentry_project: uffizzi-controller
    secrets:
      sentry_auth_token: ${{ secrets.SENTRY_AUTH_TOKEN }}

  notify:
    needs:
      - update-gke-controller
      - create-sentry-release
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/workflow-conclusion-action@v2
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ env.WORKFLOW_CONCLUSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
