name: Test, Lint, Build, and Publish Image
on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened,synchronize,reopened]

jobs:
  code-quality:
    name: Test and Lint
    uses: ./.github/workflows/code-quality.yml

  build-and-push-image:
    needs:
      - code-quality
    if: ${{ github.event_name == 'pull_request' }}
    uses: ./.github/workflows/build-and-push-image.yml
    secrets: inherit

  notify:
    needs:
      - code-quality
      - build-and-push-image
    if: ${{ always() }}
    uses: ./.github/workflows/notify.yml
    secrets: inherit

