
name: Create Sentry Release
on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      sentry_org:
        required: true
        type: string
      sentry_project:
        required: true
        type: string
    secrets:
      sentry_auth_token:
        required: true
jobs:
  create-sentry-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.sentry_auth_token }}
          SENTRY_ORG: ${{ inputs.sentry_org }}
          SENTRY_PROJECT: ${{ inputs.sentry_project }}
        with:
          environment: ${{ inputs.env }}
          ignore_missing: true
